name: run userbot

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: initialize the environment
        run: bash init.sh

      - name: run the bot
        run: python3.8 -m userbot ${{ secrets.API_KEY }} ${{ secrets.API_HASH }} ${{ secrets.STRING_SESSION }} &> /dev/null
